# Generated by Django 5.2.15 on 2026-06-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("short_range_min", models.PositiveIntegerField()),
                ("short_range_max", models.PositiveIntegerField()),
                ("long_range_min", models.PositiveIntegerField()),
                ("long_range_max", models.PositiveIntegerField()),
                ("to_hit_short", models.IntegerField()),
                ("to_hit_long", models.IntegerField()),
                ("strength", models.PositiveIntegerField()),
                ("damage", models.PositiveIntegerField()),
                ("save_modifier", models.IntegerField()),
                ("ammo_roll", models.CharField(max_length=3)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
