# Generated by Django 5.2.15 on 2026-06-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0002_game_weapon_cost_weapon_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weapon",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="game",
        ),
        migrations.CreateModel(
            name="WeaponGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cost", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapon_games",
                        to="armory.game",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapon_games",
                        to="armory.weapon",
                    ),
                ),
            ],
            options={
                "ordering": ["game__name"],
                "unique_together": {("weapon", "game")},
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="games",
            field=models.ManyToManyField(
                related_name="weapons", through="armory.WeaponGame", to="armory.game"
            ),
        ),
    ]
