# Generated by Django 5.2.15 on 2026-06-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0003_remove_weapon_cost_remove_weapon_game_weapongame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weapon",
            name="strength",
            field=models.CharField(max_length=10),
        ),
    ]
