# Generated by Django 5.2.15 on 2026-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0004_alter_weapon_strength"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapon",
            name="close_combat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weapon",
            name="template",
            field=models.BooleanField(default=False),
        ),
    ]
