# Generated by Django 5.2.15 on 2026-06-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0005_weapon_close_combat_weapon_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weapon",
            name="damage",
            field=models.CharField(max_length=10),
        ),
    ]
