# Generated by Django 5.2.15 on 2026-06-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0006_alter_weapon_damage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weapons",
                to="armory.weapontype",
            ),
        ),
    ]
