# Generated by Django 5.2.15 on 2026-06-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0007_weapontype_weapon_weapon_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="special_rules",
            field=models.ManyToManyField(
                blank=True, related_name="weapons", to="armory.specialrule"
            ),
        ),
    ]
