# Generated by Django 5.2.15 on 2026-06-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0009_remove_weapon_ammo_roll_remove_weapon_damage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponprofile",
            name="cost",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="per_shot",
            field=models.BooleanField(default=False),
        ),
    ]
