# Generated by Django 5.2.15 on 2026-06-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0010_weaponprofile_cost_weaponprofile_per_shot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponprofile",
            name="ammo_roll",
            field=models.CharField(max_length=10),
        ),
    ]
