# Generated by Django 5.2.15 on 2026-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0012_faction_weapon_faction"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
