# Generated by Django 5.2.15 on 2026-06-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0013_weaponprofile_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("movement", models.PositiveIntegerField()),
                ("weapon_skill", models.PositiveIntegerField()),
                ("ballistic_skill", models.PositiveIntegerField()),
                ("strength", models.PositiveIntegerField()),
                ("toughness", models.PositiveIntegerField()),
                ("wounds", models.PositiveIntegerField()),
                ("initiative", models.PositiveIntegerField()),
                ("attacks", models.PositiveIntegerField()),
                ("leadership", models.PositiveIntegerField()),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="armory.faction",
                    ),
                ),
                (
                    "weapon_types",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="armory.weapontype"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterGameCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cost", models.IntegerField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_games",
                        to="armory.character",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_games",
                        to="armory.game",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "game")},
            },
        ),
        migrations.AddField(
            model_name="character",
            name="games",
            field=models.ManyToManyField(
                related_name="characters", through="armory.CharacterGameCost", to="armory.game"
            ),
        ),
    ]
