# Generated by Django 5.2.15 on 2026-07-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0014_character_charactergamecost_character_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warband",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warbands",
                        to="armory.faction",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warbands",
                        to="armory.game",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WarbandMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warband_memberships",
                        to="armory.character",
                    ),
                ),
                (
                    "warband",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="armory.warband",
                    ),
                ),
            ],
            options={
                "ordering": ["character__name"],
            },
        ),
        migrations.CreateModel(
            name="WarbandMemberWeapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapons",
                        to="armory.warbandmember",
                    ),
                ),
                (
                    "weapon_game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warband_assignments",
                        to="armory.weapongame",
                    ),
                ),
            ],
            options={
                "ordering": ["weapon_game__weapon__name"],
            },
        ),
    ]
