# Generated by Django 5.2.15 on 2026-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0015_warband_warbandmember_warbandmemberweapon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warbandmember",
            options={"ordering": ["order", "character__name"]},
        ),
        migrations.AddField(
            model_name="warbandmember",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="warbandmember",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
