# Generated by Django 5.2.15 on 2026-07-05 17:11

import re
from django.db import migrations, models


def convert_profile_data(apps, schema_editor):
    """Convert string-based strength/damage/ammo_roll to structured fields."""
    WeaponProfile = apps.get_model("armory", "WeaponProfile")

    for profile in WeaponProfile.objects.all():
        # Convert strength
        old_strength = profile.strength if hasattr(profile, "strength") else "—"
        if old_strength in ("—", "-", ""):
            profile.strength_type = "none"
        elif old_strength == "special":
            profile.strength_type = "special"
        elif old_strength.startswith("User"):
            profile.strength_type = "user"
            m = re.search(r"User\s*\+\s*(\d+)", old_strength)
            profile.strength_user_bonus = int(m.group(1)) if m else 0
        else:
            try:
                profile.strength_value = int(old_strength)
                profile.strength_type = "number"
            except (ValueError, TypeError):
                # It's a dice expression like "D", "D6+2", "2D6"
                profile.strength_type = "dice"
                profile.strength_dice_expr = old_strength

        # Convert damage
        old_damage = profile.damage if hasattr(profile, "damage") else "—"
        if old_damage in ("—", "-", ""):
            profile.damage_type = "none"
        elif old_damage == "special":
            profile.damage_type = "special"
        else:
            try:
                profile.damage_value = int(old_damage)
                profile.damage_type = "number"
            except (ValueError, TypeError):
                # It's a dice expression like "D", "D3-D10", "2D6", "2D12"
                profile.damage_type = "dice"
                profile.damage_dice_expr = old_damage

        # Convert ammo_roll
        old_ammo = profile.ammo_roll if hasattr(profile, "ammo_roll") else "—"
        if old_ammo in ("—", "-", ""):
            profile.ammo_type = "none"
        elif old_ammo == "auto":
            profile.ammo_type = "auto"
        elif old_ammo == "special":
            profile.ammo_type = "special"
        else:
            # It's a target number like "2+", "4+", "6+"
            m = re.match(r"(\d+)\+", old_ammo)
            if m:
                profile.ammo_type = "target"
                profile.ammo_target = int(m.group(1))
            else:
                profile.ammo_type = "none"

        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0017_warband_user"),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name="weaponprofile",
            name="strength_type",
            field=models.CharField(
                choices=[
                    ("none", "—"),
                    ("number", "Number"),
                    ("dice", "Dice"),
                    ("user", "User"),
                    ("special", "Special"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="strength_value",
            field=models.IntegerField(blank=True, help_text="For Number type (1-10)", null=True),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="strength_dice_expr",
            field=models.CharField(
                blank=True, help_text="For Dice type (e.g., D6, 2D6, D6+2)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="strength_user_bonus",
            field=models.IntegerField(
                blank=True, help_text="For User type (0 for User, 1-3 for User+1/2/3)", null=True
            ),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="damage_type",
            field=models.CharField(
                choices=[
                    ("none", "—"),
                    ("number", "Number"),
                    ("dice", "Dice"),
                    ("special", "Special"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="damage_value",
            field=models.IntegerField(blank=True, help_text="For Number type (1-2)", null=True),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="damage_dice_expr",
            field=models.CharField(
                blank=True, help_text="For Dice type (e.g., D, D3-D10, 2D6, 2D12)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="ammo_type",
            field=models.CharField(
                choices=[
                    ("none", "—"),
                    ("target", "Target Number"),
                    ("auto", "Auto"),
                    ("special", "Special"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="weaponprofile",
            name="ammo_target",
            field=models.IntegerField(
                blank=True, help_text="For Target type (2, 4, 6 for 2+/4+/6+)", null=True
            ),
        ),
        # Run data migration
        migrations.RunPython(convert_profile_data, migrations.RunPython.noop),
        # Remove old fields
        migrations.RemoveField(
            model_name="weaponprofile",
            name="strength",
        ),
        migrations.RemoveField(
            model_name="weaponprofile",
            name="damage",
        ),
        migrations.RemoveField(
            model_name="weaponprofile",
            name="ammo_roll",
        ),
    ]
